# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: '猫咪的小鱼干'
subtitle: ''
description: overthinker
keywords:
author: '买猫咪的小鱼干'
language: zh-CN #en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://ycchen00.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next-reloaded

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
    type: git
    repo: git@github.com:ycchen00/ycchen00.github.io.git #https://ycchen00:yuchiTOMMY1234@github.com/ycchen00/ycchen00.github.io.git
    branch: master
  # - type: leancloud_counter_security_sync


feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:
  
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  model:
    use: live2d-widget-model-hijiki  #选择哪种模型
  display: #放置位置和大小
    position: left
    width: 150
    height: 300
  mobile:
    show: false #是否在手机端显示

search:
  path: search.xml
  field: post
  content: true
  format: html

# hexo-tag-cloud
tag_cloud:
    textFont: 'Trebuchet MS, Helvetica'
    textColor: '#333'
    textHeight: 20
    outlineColor: '#E2E1D1'
    maxSpeed: 0.3 # range from [0.01 ~ 1]
    pauseOnSelected: false # true means pause the cloud tag movement when highlight a tag
# Security
##

# 通用站点地图
sitemap:
  path: sitemap.xml
  
# 百度站点地图
baidusitemap:
  path: baidusitemap.xml
  
# 百度主动推送
baidu_url_submit:
  count: 5 				     ## 提交最新的1个链接
  host: tding.top 	     ## 百度站长平台中注册的域名
  token: 	 ## 准入秘钥
  path: baidu_urls.txt 		 ## 文本文档的地址， 新链接会保存在此文本文档里
  
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
  
douban:
  user: 162542457
  builtin: true
  book:
    title: '阅读'
    quote: '......'
  movie:
    title: '观影'
    quote: '......'
  timeout: 10000
  
leancloud_counter_security:
  enable_sync: false
  app_id: Q6HNGTtOPGta1RiawrPGfDug-MdYXbMMI
  app_key: T9ijybUJinTN0Ndp7CysyFMl
  # server_url: https://ycchen00.github.io
  username: ycchen00
  password: yuchiTOMMY1234
